# Generated by Django 5.1.1 on 2024-10-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(default='img-1.jpg', upload_to='upload/')),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
